boilerplate: updated
Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>

diff --git a/utils/makefile.python b/utils/makefile.python
--- a/utils/makefile.python
+++ b/utils/makefile.python
@@ -10,9 +10,21 @@ PYBUILD  ?= py_build
 # python version to use
 PY       ?=3
 PYTHON   ?= python$(PY)
-PIP      ?= pip$(PY)
-PIP_INST ?= --user
+PIP_INST ?=
 PYLINT   ?= pylint
+
+VIRTUALENV   = virtualenv --python=$(PYTHON)
+VTENV_OPTS   = "--no-site-packages"
+PY_ENV       = ./local/py$(PY)
+PY_ENV_BIN   = $(PY_ENV)/bin
+
+ifeq ($(KBUILD_VERBOSE),1)
+  PIP_VERBOSE =
+  VIRTUALENV_VERBOSE =
+else
+  PIP_VERBOSE = "-q"
+  VIRTUALENV_VERBOSE = "-q"
+endif
 
 python-help::
 	@echo  'makefile.python:'
@@ -25,15 +37,14 @@ python-help::
 	@echo  ''
 	@echo  '  make PY=2  [targets] => to eval targets with python 2 (default 3)'
 	@echo  '  make PYLINT=pylint3  => to use pylint3 (default is standard pylint)'
-	@echo  '  make PIP_INST=...    => to set/unset pip install options (default "--user")'
+	@echo  '  make PIP_INST=...    => to set/unset pip install options'
 
 
 # ------------------------------------------------------------------------------
 # requirements
 # ------------------------------------------------------------------------------
 
-PHONY += msg-pylint-exe pylint-exe
-
+PHONY += msg-python-exe python-exe
 msg-python-exe:
 	@echo "\n  $(PYTHON) is required\n\n\
   Make sure you have an $(PYTHON) installed, grab it from\n\
@@ -50,59 +61,57 @@ python-exe:
 	@:
 endif
 
-msg-pylint-exe:
-	@echo "\n  $(PYLINT) is required\n\n\
-  Make sure you have an updated pylint installed, grab it from\n\
-  https://www.pylint.org or install it from your package\n\
-  manager. On debian based OS these requirements are\n\
-  installed by::\n\n\
-    sudo apt-get install pylint\n" | $(FMT)
+PHONY += msg-virtualenv-exe virtualenv-exe
+msg-virtualenv-exe:
+	@echo "\n  virtualenv is required\n\n\
+  Make sure you have an updated virtualenv installed, grab it from\n\
+  https://virtualenv.pypa.io/en/stable/installation/ or install it\n\
+  via pip by::\n\n\
+    pip install --user virtualenv\n" | $(FMT)
 
-ifeq ($(shell which $(PYLINT) >/dev/null 2>&1; echo $$?), 1)
-pylint-exe: msg-pylint-exe
-	$(error The '$(PYLINT)' command was not found)
+ifeq ($(shell which virtualenv >/dev/null 2>&1; echo $$?), 1)
+virtualenv-exe: msg-virtualenv-exe
+	$(error The 'virtualenv' command was not found)
 else
-pylint-exe:
+virtualenv-exe:
 	@:
 endif
 
-msg-pip-exe:
-	@echo "\n  $(PIP) is required\n\n\
-  Make sure you have an updated pip installed, grab it from\n\
-  https://pip.pypa.io or install it from your package\n\
-  manager. On debian based OS these requirements are\n\
-  installed by::\n\n\
-    sudo apt-get install python$(PY)-pip\n" | $(FMT)
-
-ifeq ($(shell which $(PIP) >/dev/null 2>&1; echo $$?), 1)
-pip-exe: msg-pip-exe
-	$(error The '$(PIP)' command was not found)
-else
-pip-exe:
-	@:
-endif
+PHONY += pylint-exe
+pylint-exe: $(PY_ENV)
+	$(PY_ENV_BIN)/pip $(PIP_VERBOSE) install $(PYLINT)
 
 # ------------------------------------------------------------------------------
 # commands
 # ------------------------------------------------------------------------------
 
+# $2 path to folder where virtualenv take place
+quiet_cmd_virtualenv  = PYENV     $@
+      cmd_virtualenv  = \
+	if [ ! -d "./$(PY_ENV)" ];then                                  \
+		$(VIRTUALENV) $(VIRTUALENV_VERBOSE) $(VTENV_OPTS) $2;   \
+	else                                                            \
+		echo "using virtualenv from $2";                        \
+        fi
+
+
 # $2 path to folder with setup.py
 quiet_cmd_pyinstall   = INSTALL   $@
-      cmd_pyinstall   = $(PIP) install $(PIP_INST)  -e $2
+      cmd_pyinstall   = $(PY_ENV_BIN)/pip $(PIP_VERBOSE) install $(PIP_INST) -e $2
 
 # Uninstall the package. Since pip does not uninstall the no longer needed
 # depencies (something like autoremove) the depencies remain.
 
 # $2 package name to uninstall
 quiet_cmd_pyuninstall = UNINSTALL $@
-      cmd_pyuninstall = $(PIP) uninstall $2
+      cmd_pyuninstall = $(PY_ENV_BIN)/pip $(PIP_VERBOSE) uninstall --yes $2
 
 # $2 path to lint
 quiet_cmd_pylint      = LINT      $@
-      cmd_pylint      = $(PYLINT) --rcfile utils/pylintrc $2
+      cmd_pylint      = $(PY_ENV_BIN)/$(PYLINT) --rcfile utils/pylintrc $2
 
 quiet_cmd_pytest      = TEST      $@
-      cmd_pytest      = cd tests; $(PYTHON) run.py -I py35 -d -m '^[tT]est' $(TEST)
+      cmd_pytest      = $(PY_ENV_BIN)/tox -vv
 
 # setuptools, pip, easy_install its a mess full of cracks, a documentation hell
 # and broken by design ... all sucks, I really, really hate all this ... aaargh!
@@ -110,14 +119,14 @@ quiet_cmd_pytest      = TEST      $@
 # sdist: https://packaging.python.org/distributing/#source-distributions
 # bdist_wheel: https://packaging.python.org/distributing/#pure-python-wheels
 quiet_cmd_pybuild     = BUILD     $@
-      cmd_pybuild     = $(PYTHON) setup.py \
+      cmd_pybuild     = $(PY_ENV_BIN)/$(PYTHON) setup.py \
 			sdist -d $(PYDIST)  \
 			bdist_wheel --bdist-dir $(PYBUILD) -d $(PYDIST)
 
 quiet_cmd_pyclean     = CLEAN     $@
 # remove 'build' folder since bdist_wheel does not care the --bdist-dir
       cmd_pyclean     = \
-	rm -rf $(PYDIST) build *.egg-info          ;\
+	rm -rf $(PYDIST) $(PYBUILD) ./local *.egg-info     ;\
 	find . -name '*.pyc' -exec rm -f {} +      ;\
 	find . -name '*.pyo' -exec rm -f {} +      ;\
 	find . -name __pycache__ -exec rm -rf {} +
@@ -142,11 +151,14 @@ pylint: pylint-exe
 	$(call cmd,pylint,$(PYOBJECTS))
 
 PHONY += pyinstall pyuninstall
-pyinstall: pip-exe
+pyinstall:
 	$(call cmd,pyinstall,.)
-pyuninstall: pip-exe
+pyuninstall:
 	$(call cmd,pyuninstall,$(PYOBJECTS))
 
+$(PY_ENV): virtualenv-exe python-exe
+	$(call cmd,virtualenv,$(PY_ENV))
+	@$(PY_ENV_BIN)/pip install $(PIP_VERBOSE) -r requirements.txt
 
 # With 'dependency_links=' setuptools supports dependencies on packages hosted
 # on other reposetories then PyPi, see "Packages Not On PyPI" [1].  The big
